language: rust
cache: cargo

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

addons:
  apt:
    update: true
    packages:
      - sendmail
      - clang

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
